name: ss_market
description: "Professional Share Market App"
publish_to: 'none'
version: 1.0.0+12

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4 # ✅
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0

  in_app_purchase: ^3.2.0 # Check for latest version

  google_fonts: ^6.2.1
  fl_chart: ^0.70.2 # Required for the stock charts
  firebase_auth: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0D1117" # Matches your app's background
  adaptive_icon_foreground: "assets/icon/icon.png" # The logo part
  # Optional: monochrome icon for Android 13+ themed icons
  monochrome_icon: "assets/icon/icon.png"

flutter:
  uses-material-design: true