name: ss_market
description: "Professional Share Market App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0

  google_fonts: ^6.2.1
  fl_chart: ^0.70.2 # Required for the stock charts
  firebase_auth: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true